name: Auto Release on Version Change

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.extract_version.outputs.version }}
      should_release: ${{ steps.version_check.outputs.should_release }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current version
        id: extract_version
        run: |
          VERSION=$(grep -oP '__version__ = "\K[0-9]+\.[0-9]+\.[0-9]+' src/roksana/__init__.py)
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$VERSION"

      - name: Check if version exists as a tag
        id: version_check
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/v$VERSION"; then
            echo "Version $VERSION already exists."
            echo "::set-output name=should_release::false"
          else
            echo "New version detected: $VERSION"
            echo "::set-output name=should_release::true"
          fi

  create-release:
    needs: check-version
    if: needs.check-version.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create new Git tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag -a "v${{ needs.check-version.outputs.new_version }}" -m "Release v${{ needs.check-version.outputs.new_version }}"
          git push origin "v${{ needs.check-version.outputs.new_version }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ needs.check-version.outputs.new_version }}"
          name: "Release v${{ needs.check-version.outputs.new_version }}"
          body: "Automated release for version v${{ needs.check-version.outputs.new_version }}"
          draft: false
          prerelease: false
